=== SysAdminDoc/android-debloat-list/schema/bloatware_list.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://muntashirakon.github.io/android-debloat-list/bloatware_list.json",
    "title": "Bloatware List",
    "description": "Listing of Android bloatware",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "description": "Bloatware package name",
                "type": "string"
            },
            "label": {
                "description": "Bloatware package label",
                "type": "string"
            },
            "dependencies": {
                "description": "Packages that this bloatware depends on",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "required_by": {
                "description": "Packages that depend on this bloatware",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "tags": {
                "description": "Predefined tags",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "description": {
                "description": "Bloatware description",
                "type": "string"
            },
            "web": {
                "description": "Online references",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "removal": {
                "description": "Bloatware removal type (delete, replace, caution, unsafe)",
                "type": "string",
                "enum": [
                    "delete",
                    "replace",
                    "caution",
                    "unsafe"
                ]
            },
            "warning": {
                "description": "Possible consequences of removing the bloatware (for caution and unsafe), for others, useful information",
                "type": "string"
            },
            "suggestions": {
                "description": "Suggestion ID for listing alternatives to this bloatware",
                "type": "string"
            },
            "suppress": {
                "description": "Suppress a particular warning issued by the linter, separated by comma without space",
                "type": "string"
            }
        },
        "required": [
            "id",
            "description",
            "removal"
        ]
    },
    "uniqueItems": true
}

=== SysAdminDoc/android-debloat-list/google.json
[
    {
        "id": "com.android.chrome",
        "label": "Google Chrome",
        "description": "Google Chrome: Slow & Painful\nOccasionally runs in the background, not to mention how it tracks everything.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.android.chrome",
            "https://privacytests.org/android.html",
            "https://fidoalliance.org/passkeys/"
        ],
        "removal": "replace",
        "warning": "Removing the app may break creating and storing passkeys on your phone, so keep this enabled if you want to use that form of authentication. Google Play Services can also provide this functionality on some devices. When Chrome is updated via the Play Store, the Trichrome Library is also updated automatically. If Chrome is disabled or removed, it may impact WebView functionality.\nThis is because Chrome, WebView, and the Trichrome Library work together as a bundle starting from Android 10 (API 29) and above.",
        "suggestions": "browsers"
    },
    {
        "id": "com.android.hotwordenrollment.okgoogle",
        "label": "OK Google enrollment",
        "description": "\"OK Google\" detection service that hears everything.",
        "removal": "delete"
    },
    {
        "id": "com.android.hotwordenrollment.xgoogle",
        "label": "Google Assistant",
        "description": "Formerly, X Google enrollment. \"OK Google\" detection service that hears everything.",
        "removal": "delete"
    },
    {
        "id": "com.android.partnerbrowsercustomizations.chromeHomepage",
        "label": "com.android.partnerbrowsercustomizations.chromeHomepage",
        "description": "Horrible stuff for Google Chrome. This package bypass your DNS settings (for letting pass Google ads).",
        "removal": "delete"
    },
    {
        "id": "com.android.soundpicker",
        "label": "Sounds",
        "description": "Needed to pick up a phone ringtone. No weird permissions.",
        "web": [
            "https://beta.pithus.org/report/f5f7c265c6d98666c78267b91643bbfb635021d5d4f85c93407079ba4aad88ee"
        ],
        "removal": "caution"
    },
    {
        "id": "com.android.systemui.plugin.globalactions.wallet",
        "label": "com.android.systemui.plugin.globalactions.wallet",
        "description": "Apk file name: QuickAccessWallet. This is the Google Pay widget in the power menu(hold power button for 1sec to show this menu), below the Emergency, Power off and Reboot buttons.",
        "removal": "delete",
        "suppress": "LabelSameAsId"
    },
    {
        "id": "com.android.vending",
        "label": "Google Play Store",
        "description": "The malware delivery store. Most apps are full of ads, trackers and malware.",
        "web": [
            "https://www.xda-developers.com/google-play-store-more-safety/"
        ],
        "removal": "caution",
        "suggestions": "app_stores"
    },
    {
        "id": "com.chrome.beta",
        "label": "Chrome Beta",
        "description": "The beta version of Google Chrome.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.chrome.beta"
        ],
        "removal": "replace",
        "suggestions": "browsers"
    },
    {
        "id": "com.chrome.canary",
        "label": "Chrome Canary (Unstable)",
        "description": "Canary version of Google Chrome, usually provides nightly builds.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.chrome.canary"
        ],
        "removal": "replace",
        "suggestions": "browsers"
    },
    {
        "id": "com.chrome.dev",
        "label": "Chrome Dev",
        "description": "Google Chrome developer edition.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.chrome.dev"
        ],
        "removal": "replace",
        "suggestions": "browsers"
    },
    {
        "id": "com.google.android.GoogleCamera",
        "label": "Google Camera",
        "description": "Camera with incredible features with the cost of tracking. Try the tracker-free mods if you're too much into Google Camera.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.GoogleCamera"
        ],
        "removal": "replace",
        "suggestions": "cameras"
    },
    {
        "id": "com.google.android.accessibility.soundamplifier",
        "description": "Accessibility sound amplifier (https://play.google.com/store/apps/details?id=com.google.android.accessibility.soundamplifier)",
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.access.wifi.consumer",
        "label": "Google Wifi",
        "description": "Google Wifi app",
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.adm",
        "label": "Google Find My Device",
        "description": "Lets you locate your Android device.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.adm"
        ],
        "removal": "delete",
        "suggestions": "locators"
    },
    {
        "id": "com.google.android.apps.ads.publisher",
        "label": "Google AdSense",
        "description": "Google Adsense app",
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.adwords",
        "label": "Google Ads",
        "description": "Lets you monitor your ad campaigns.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.adwords"
        ],
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.assistant",
        "label": "Google Assistant Go",
        "description": "Lightweight Google Assistant for low-end devices (Go edition)",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.assistant"
        ],
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.authenticator2",
        "label": "Google Authenticator",
        "description": "Generates 2-Step Verification codes on your phone.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2"
        ],
        "removal": "replace",
        "suggestions": "authenticators"
    },
    {
        "id": "com.google.android.apps.blogger",
        "label": "Blogger",
        "description": "Official app for Blogger/blogspot.com",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.blogger"
        ],
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.books",
        "label": "Google Play Books",
        "description": "Lets you buy and read ebooks, audiobooks, comics and manga.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.books"
        ],
        "removal": "replace",
        "suggestions": "ebook_readers"
    },
    {
        "id": "com.google.android.apps.chromecast.app",
        "label": "Google Home",
        "description": "Lets you set up, manage, and control your Google Nest, Google Wifi, Google Home and Chromecast devices. Let Google harvest your data with your money.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app"
        ],
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.cloudprint",
        "label": "Cloud Print",
        "description": "Let you print anywhere from any Android tablet or smartphone via Google.",
        "removal": "replace"
    },
    {
        "id": "com.google.android.apps.cultural",
        "label": "Google Arts & Culture",
        "description": "Know and interact with arts but with a price: Your privacy.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.cultural"
        ],
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.currents",
        "label": "Google Currents",
        "description": "Discontinued.",
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.docs",
        "label": "Google Drive",
        "description": "The drive where no personal data should ever be kept unencrypted.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.docs"
        ],
        "removal": "delete",
        "suggestions": "cloud_services"
    },
    {
        "id": "com.google.android.apps.docs.editors.docs",
        "label": "Google Docs",
        "description": "Google Docs client for Android",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.docs"
        ],
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.docs.editors.sheets",
        "label": "Google Sheets",
        "description": "Google Sheets client for Android",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.sheets"
        ],
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.docs.editors.slides",
        "label": "Google Slides",
        "description": "Google Slides client for Android",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.slides"
        ],
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.dynamite",
        "label": "Google Chat",
        "description": "Previously Hangout Chat, is a communication and collaboration tool focusing on conversation.",
        "web": [
            "https://play.google.com/store/apps/details?id=com.google.android.apps.dynamite"
        ],
        "removal": "delete"
    },
    {
        "id": "com.google.android.apps.enterprise.cpanel",
        "label": "Google Admin",
